Add example with multiple available debug symbols (source maps and DW…
bmeurer/emscripten-dbg-stories pull request #10
Opened 2024-07-29 08:46 UTC by ktran

Adds an example for debugging WebAssembly with multiple debug symbol sources available (source maps + DWARF).

2024-07-29 09:43 UTC, bmeurer requested changes
I think you forgot to add the new files 😄

2024-07-29 10:05 UTC, ktran commented
The new examples are based on an existing `hello.c` file, so it should be fine like this. The checks seem to be related to some other issue that is unrelated with not finding `/opt/buildhome/python3.7/bin/activate`, I can have a look at that!

2024-07-29 13:07 UTC, ktran commented
Force pushing doesn't seem to re-trigger the netlify bot, I'll re-request the review :)

2024-07-30 06:11 UTC, bmeurer commented
> The new examples are based on an existing `hello.c` file, so it should be fine like this. The checks seem to be related to some other issue that is unrelated with not finding `/opt/buildhome/python3.7/bin/activate`, I can have a look at that!

Ah, of course. 😁  I missed that part in the `Makefile`.

2024-07-30 06:11 UTC, bmeurer approved these changes

2024-07-30 06:11 UTC, merged